services:
  authelia:
    container_name: authelia
    image: authelia/authelia:4.39.13
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/authelia/config:/config
    environment:
      TZ: ${TZ}
    ports:
      - ${PORT}:9091
  redis:
    container_name: authelia_redis
    image: redis:7-alpine
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: