services:
  server:
    container_name: home_assistant
    restart: unless-stopped
    image: homeassistant/home-assistant:2025.11
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/home-assistant/config:/config