services:
  app:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:1.0.2
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - ${PORT}:8080
    volumes:
      - ${CONFIG_DIR}/stirling-pdf/tessdata:/usr/share/tessdata
      - ${CONFIG_DIR}/stirling-pdf/configs:/configs
      - ${CONFIG_DIR}/stirling-pdf/logs:/logs
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
      LANGS: ALL