services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:2025-07-01
    restart: unless-stopped
    ports:
      - ${PORT}:8081
    volumes:
      -  ${MEDIA_LIBRARY_DIR}/metube:/downloads
    environment:
      - DELETE_FILE_ON_TRASHCAN=true